### ISSUE TITLE
[Question] Does your example can be deployed on S3 only?

### ISSUE THREAD

**Issue by gustavoca** [tomimick/tm-nextjs-starter#1]
Hello looking around i see that nextjs is a framework that does SSR...  and ive seen that many people use express for it... but in your example i see u dont?

So my question would be, can this example be run on a S3 bucket only?

PS. im very new to front end dev, so please be gentle :)

**Comment by tomimick** [comment]
Yes, putting files to S3 works.

I have found netlify.com to be a convenient solution for hosting static sites.
